rapport:
	@pdflatex rapport.tex && pdflatex rapport.tex && echo -e "\033[42m\n\t\033[1;37mRAPPORT.PDF : SUCCESS\033[21m\n\033[0m" || echo -e "\033[41m\n\t\033[1;37mRAPPORT.PDF : ERROR\033[21m\n\033[0m"

clean:
	@rm -f *.log *.aux *.toc *.pdf && echo -e "\033[42m\n\t\033[1;37mCLEAN : SUCCESS\033[21m\n\033[0m" || echo -e "\033[41m\n\t\033[1;37mCLEAN : ERROR\033[21m\n\033[0m"

