rapport:
	@pdflatex rapport.tex && pdflatex rapport.tex && echo -e "\e[42m\n\t\e[1;37mRAPPORT.PDF : SUCCESS\e[21m\n\e[0m" || echo -e "\e[41m\n\t\e[1;37mRAPPORT.PDF : ERROR\e[21m\n\e[0m"

clean:
	@rm -f *.log *.aux *.toc *.pdf && echo -e "\e[42m\n\t\e[1;37mCLEAN : SUCCESS\e[21m\n\e[0m" || echo -e "\e[41m\n\t\e[1;37mCLEAN : ERROR\e[21m\n\e[0m"

